### ISSUE TITLE
git config user.name and user.email should be defined

### ISSUE THREAD

**Issue by niooss-ledger** [synacktiv/nord-stream#4]
Hello,
First, thank you for publishing this great tool! It seems very useful. I tried using it and it failed in my test environment because `git` was not configured. More precisely, when `nord-stream` tried to use `git commit`, it failed with:

```text
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@a8ba5aecd84a.(none)')
```

I fixed this issue by running both `git config --global ...` commands.

Anyway, during assessments, it would be useful to use custom name and email in git. I suggest using `git config user.email ...` and `git config user.name ...` in https://github.com/synacktiv/nord-stream/blob/11c7cecbac6e3f11f220e5c3fe6a9a50e40f282b/nordstream/git.py#L24-L31  What do you think?

By the way, debugging this issue was hard because the output of `git commit` was eaten away due to using `stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL` in `gitRunCommand`. It would also be nice to have a `--debug-subprocess` option which would make the output of subprocesses launched by `gitRunCommand` appear.

**Comment by hugo-syn** [comment]
Hello, I've added some check to add an email/Name if it's not already configured. I've also added full debug on the git commands which are executed on the host, you should be able to see them with `-d`

Let me know if it resolves your problem :)

**Comment by niooss-ledger** [comment]
Thanks for your quick fix! I confirm https://github.com/synacktiv/nord-stream/commit/fcecc6461eb9b604f1f011fc11e48170c363f464 fixed this issue.

By the way, I was surprised by `if logger.level <= 10:` but it seems correct according to [Python's documentation](https://docs.python.org/3.10/library/logging.html#logging-levels) to filter "only when the log level is debug". I learned something new :smiley:
